### ISSUE TITLE
com.aries.extension의 레포지토리 알려주시겠습니까?

### ISSUE THREAD

**Issue by minsoo-jun** [jennifersoft/jennifer-view-batch-tutorial#1]
안녕하세요.
작성 해주신 플러그인을 항상 잘 쓰고 있습니다. 이번에 레포트 용으로 플러그인을 만들어 볼까 해서 batch의 내용을 보고 있습니다만,
상기 라이브러리가 메이븐 센트랄 레포지토리와 구글등에도 등록이 안되어 있는 것 같습니다만, 취득 가능한 레포지토리를 알려주시겠습니까?

**Comment by seogi1004** [comment]
안녕하세요. 제니퍼소프트 홍재석 과장입니다.

일단 maven은 센트럴에 올리지 않고, 저희 회사에서 운영하는 서버에 올려두었습니다.
경로는 아래와 같습니다.
http://support.jennifersoft.com:8081/nexus/content/groups/public/com/aries/extension/

개발하실 때, tutorial 프로젝트를 참고하시면 좋습니다.
해당 pom.xml에 라이브러리 저장소가 세팅되어 있습니다.
https://github.com/jennifersoft/jennifer-view-plugin-tutorial/blob/master/pom.xml

감사합니다.

2018년 11월 13일 (화) 오전 9:36, minsoo-jun <notifications@github.com>님이 작성:

**Comment by seogi1004** [comment]
죄송합니다. 튜토리얼 프로젝트를 잘못 공유드렸습니다.

아래 링크를 참고하시면 됩니다.
https://github.com/jennifersoft/jennifer-view-batch-tutorial

2018년 11월 13일 (화) 오전 10:14, 1명왕 <seogi777@gmail.com>님이 작성:

**Comment by minsoo-jun** [comment]
안녕하세요. 오늘 시간이 되어서 다시 시도 해보고 있는 중입니다만 아래와 같은 에러가 나고 있습니다.
`2018-11-14 17:02:30.657 [qtp149047107-19] ERROR com.aries.view.web.BaseController - Request(GET /extension/batch/run?id=domain_metrics_batch&batchTime=1542034800000)@55a17615
2018-11-14 17:02:30.659 [qtp149047107-19] ERROR com.aries.view.web.BaseController - java.lang.ArrayIndexOutOfBoundsException: 0
	at com.aries.view.cache.BatchCacheManager.runWorker(BatchCacheManager.java:120)
	at com.aries.view.web.ExtensionController.runBatchWorker(ExtensionController.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.aries.view.filter.FrontFilter.doFilter(FrontFilter.java:99)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.aries.view.filter.EnforceHTTPSFilter.doFilter(EnforceHTTPSFilter.java:53)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)`
Jar파일의 등록은 Adapter and Plugin의 Backup에 아래의 그림과 같이 등록 했고, 혹시나 해서 Option 에서 발급한 token을 변수로 설정 했습니다.
![screen shot 2018-11-14 at 17 11 23](https://user-images.githubusercontent.com/2956728/48468826-595ad780-e830-11e8-9e09-2535926f8599.png)

소스 변경 사항은 DomainMetricsBatch 클라스의 System.out.println을 LogUtil.info("Domain ID : " + data.domainId); 로 바꾸었고 다시 jar로 패키징 했습니다.
패키징한 jar파일은 아래와 같습니다.
(확장자 zip을 jar로 변경하셔야 합니다.)
[jennifer_batch.zip](https://github.com/jennifersoft/jennifer-view-batch-tutorial/files/2579734/jennifer_batch.zip)

해결책이 있을까요?
감사합니다.

**Comment by seogi1004** [comment]
일단 클래스 명시가 안되어 있네요?
삭제하시고, 클래스를 패키지명까지 정확하게 입력해주세요.

그리고 튜토리얼 프로젝트의 pom.xml를 사용해서 빌드하셔야 합니다.
제니퍼 뷰서버에 불필요한 jar가 추가되면 안됩니다.

2018년 11월 14일 (수) 오후 5:15, minsoo-jun <notifications@github.com>님이 작성:

**Comment by minsoo-jun** [comment]
답변이 늦었습니다. 저희 내부 레포지토리와 충돌이 있었습니다. 현재는 잘 작동되고 있습니다, 감사합니다.

**Comment by minsoo-jun** [comment]
감사합니다. 최종적으로는 realtimeapi를 참조 해서 prometheus에 정보를 보낼수 있게 되었습니다.
https://github.com/minsoo-jun/jennifer-view-plugin-promethus

**Comment by seogi1004** [comment]
고생하셨습니다! 잘 만드셨네요!!

플러그인은 API로도 많이 사용하고 있습니다. ㅎㅎ
보통 피치못한 사정으로 인해 고객사 커스터마이징 해줄 때, 개발하곤 합니다!

2018년 11월 22일 (목) 오후 6:54, minsoo-jun <notifications@github.com>님이 작성:
